"""Infersoft Python SDK."""

from __future__ import annotations

from . import selectors
from ._client import AsyncClient, Client
from ._version import __version__
from .errors import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    CreditsLimitExceededError,
    DownloadTransferError,
    ExtractError,
    ForbiddenError,
    InfersoftError,
    NotFoundError,
    PayloadTooLargeError,
    PreconditionFailedError,
    RateLimitError,
    ServerError,
    UnauthorizedError,
    UnprocessableEntityError,
    UploadManyError,
    UploadTransferError,
    WaitTimeoutError,
)
from .models import (
    AssignDocumentsResult,
    BatchUploadResponse,
    BulkDeleteResult,
    CreditsEstimate,
    CreditsQuote,
    DataTypeName,
    DocumentExtractionResultItem,
    DocumentPage,
    DocumentStatus,
    DocumentSummary,
    DownloadResponse,
    ExtractionResultValue,
    ExtractionTracebackBBox,
    ExtractionTracebackItem,
    ExtractResult,
    FileOutcome,
    Folder,
    FolderBulkDeleteResult,
    FolderMoveResult,
    FolderPage,
    FolderPathResult,
    FolderPathsResult,
    Job,
    JobPage,
    JobStatus,
    MoveResult,
    Project,
    ProjectPage,
    PromptMeta,
    PromptPage,
    Tag,
    UploadDuplicate,
    UploadErrorInfo,
    UploadItem,
    UploadResult,
)
from .resources.documents import MAX_BATCH_FILES
from .selectors import (
    build_created_at_selector,
    build_document_class_selector,
    build_file_selector,
    build_folder_selector,
    build_has_children_selector,
    build_has_running_workflow_selector,
    build_is_valid_selector,
    build_job_selector,
    build_name_selector,
    build_page_count_selector,
    build_project_selector,
    build_selectors,
    build_size_selector,
    build_source_document_selector,
    build_tag_selector,
)

__all__ = [
    "Client",
    "AsyncClient",
    "MAX_BATCH_FILES",
    "__version__",
    # selectors
    "selectors",
    "build_selectors",
    "build_file_selector",
    "build_folder_selector",
    "build_name_selector",
    "build_document_class_selector",
    "build_tag_selector",
    "build_created_at_selector",
    "build_size_selector",
    "build_page_count_selector",
    "build_source_document_selector",
    "build_project_selector",
    "build_job_selector",
    "build_is_valid_selector",
    "build_has_children_selector",
    "build_has_running_workflow_selector",
    # errors
    "InfersoftError",
    "AuthenticationError",
    "APIConnectionError",
    "APITimeoutError",
    "UploadManyError",
    "DownloadTransferError",
    "UploadTransferError",
    "WaitTimeoutError",
    "APIError",
    "BadRequestError",
    "UnauthorizedError",
    "ForbiddenError",
    "NotFoundError",
    "ConflictError",
    "CreditsLimitExceededError",
    "ExtractError",
    "PreconditionFailedError",
    "PayloadTooLargeError",
    "UnprocessableEntityError",
    "RateLimitError",
    "ServerError",
    # models
    "AssignDocumentsResult",
    "BatchUploadResponse",
    "BulkDeleteResult",
    "CreditsEstimate",
    "CreditsQuote",
    "DataTypeName",
    "DocumentExtractionResultItem",
    "DocumentPage",
    "DocumentStatus",
    "DocumentSummary",
    "DownloadResponse",
    "ExtractionResultValue",
    "ExtractionTracebackBBox",
    "ExtractionTracebackItem",
    "ExtractResult",
    "FileOutcome",
    "Folder",
    "FolderBulkDeleteResult",
    "FolderMoveResult",
    "FolderPage",
    "FolderPathResult",
    "FolderPathsResult",
    "Job",
    "JobPage",
    "JobStatus",
    "MoveResult",
    "Project",
    "ProjectPage",
    "PromptMeta",
    "PromptPage",
    "Tag",
    "UploadDuplicate",
    "UploadErrorInfo",
    "UploadItem",
    "UploadResult",
]
